### ISSUE TITLE
webpack-dev-server --hot error

### ISSUE THREAD

**Issue by crh225** [damienbod/Angular2WebpackVisualStudio#2]
I am getting an error when running the webpack server hot. Great app BTW!

Error: CopyWebpackPlugin: to use webpack-dev-server, devServer.outputPath must be defined in the webpack config
    at getOutputDir (C:\dev\VS2015\ng\Angular2WebpackVisualStudio-master\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\node_modules\copy-webpack-plugin\dist\index.js:56:15)
    at Object.apply (C:\dev\VS2015\ng\Angular2WebpackVisualStudio-master\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\node_modules\copy-webpack-plugin\dist\index.js:72:26)
    at Compiler.apply (C:\Users\housec\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (C:\Users\housec\AppData\Roaming\npm\node_modules\webpack\lib\WebpackOptionsApply.js:62:18)
    at webpack (C:\Users\housec\AppData\Roaming\npm\node_modules\webpack\lib\webpack.js:22:48)
    at Object.<anonymous> (C:\Users\housec\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:158:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
Process terminated with code 1.

**Comment by damienbod** [comment]
Thanks
@FabianGosebrink have you any idea here? I can't look at this till next week.

Greetings Damien

**Comment by FabianGosebrink** [comment]
Hey, as far as I can see we do not have webpack-dev-server included (yet). Maybe a good feature. Will try to include it next week.
BR
Fabian

**Comment by crh225** [comment]
I ended up doing somthing like:
    config.output = {
        path: root('./wwwroot'),
        publicPath: isProd ? '' : 'http://localhost:5000/',
        filename: outputfilename,
        chunkFilename: isProd ? '[id].[hash].chunk.js' : '[id].chunk.js',
        devServer: {
            //I'm not sure if this is the one that is needed or the one below, so I used both.
            outputPath: root('./wwwroot'),
        }
    };

    config.devServer = {
        // This is required for webpack-dev-server if using a version <3.0.0. 
        // The path should be an absolute path to your build destination. 
            outputPath: path.join(__dirname, 'build')
    };

to run: I had to change the port in the index.html file from 5000 to port 8080 (for the server) and then run in webpack via command line webpack-dev-server --progress --inline. I could never get webpack-dev-server --hot to work.

**Comment by FabianGosebrink** [comment]
I will include the dev-server tomorrow :)

**Comment by FabianGosebrink** [comment]
I created a development-branch in case you want to take a sneak peek. There the dev-server is availbale through the "npm start" command and I seperated the dev- and prod-file of webpack.
HTH

**Comment by FabianGosebrink** [comment]
@damienbod and me just merged a set of changes including the dev-server. You should not see any error anymore. 
HTH

BR from @damienbod and me :)
